# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-27 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_project_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
