# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-27 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_project_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='joined_group', to='project_app.User'),
        ),
    ]
